name: Commit Workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          ndoe-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run project
        run: npm run dev