name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main
      - develop
      - release

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Switch to the activity branch
        run: git checkout ${{ github.head_ref }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Compile Typescript
        run: npx tsc

      - name: Run project
        run: npm start
